CREATE TABLESPACE hce_cmstbls DATAFILE 'pres.dbf' SIZE 100M AUTOEXTEND ON NEXT 10M MAXSIZE 600M;
-- USERS
CREATE USER pres IDENTIFIED BY pres
DEFAULT TABLESPACE pres
TEMPORARY TABLESPACE temp;
GRANT CONNECT TO pres;
GRANT RESOURCE TO pres;
GRANT CREATE ANY SYNONYM TO pres;

commit;